global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'parser-service'
    static_configs:
      - targets: ['localhost:8081']
    metrics_path: '/metrics'

  - job_name: 'workout-service'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: '/metrics'

  - job_name: 'projection-service'
    static_configs:
      - targets: ['localhost:8083']
    metrics_path: '/metrics'

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['localhost:8084']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['localhost:8085']
    metrics_path: '/metrics'
